### ISSUE TITLE
[Live Chat] [design] message date time published

### ISSUE THREAD

**Issue by cutbypham** [OngDev/client#10]
https://www.figma.com/file/OuRDleEDRc6unR2us8OrXW/Ong-Dev-OBS-background?node-id=7%3A461

#2

**Comment by kcvdk3101** [comment]
### **DONE**
[Figma Ong Dev Live Chat v2](https://www.figma.com/file/OuRDleEDRc6unR2us8OrXW/Ong-Dev-Live-Chat-v2?node-id=0%3A1)

**Comment by cutbypham** [comment]
> ### **DONE**
> [Figma Ong Dev Live Chat v2](https://www.figma.com/file/OuRDleEDRc6unR2us8OrXW/Ong-Dev-Live-Chat-v2?node-id=0%3A1)
