### ISSUE TITLE
[live chat] sort button

### ISSUE THREAD

**Issue by cutbypham** [OngDev/client#27]

**Comment by kcvdk3101** [comment]
[Sort Button](https://www.figma.com/file/OuRDleEDRc6unR2us8OrXW/Ong-Dev-Live-Chat-v2)

**Comment by cutbypham** [comment]
![image](https://user-images.githubusercontent.com/40050527/130323684-68054f14-6473-4ee2-b9e6-76a4f18c2d18.png)
